### ISSUE TITLE
papéis e responsabilidades

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-GummyLog#19]
todos da equipe devem participar das atividades, e não apenas um ou duas pessoas.
Ajustem, por favor, e façam isso acontecer no dia a dia da equipe.

![image](https://github.com/mdsreq-fga-unb/2023.2-GummyLog/assets/68402547/a63e711d-1984-4f4d-8c32-e7aedf5de12a)

**Comment by Dridr1** [comment]
Alterados os participantes de cada atividade
