### ISSUE TITLE
Planejamento

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-GummyLog#21]
Todas as sprints devem estar definidas até o final da disciplina.

![image](https://github.com/mdsreq-fga-unb/2023.2-GummyLog/assets/68402547/555e564e-2c3d-43ac-9426-e4d9d8485d56)

**Comment by Dridr1** [comment]
Adicionado todo o cronograma sincronizado com o cronograma da disciplina
