### ISSUE TITLE
XP

### ISSUE THREAD

**Issue by marsicanogeorge** [mdsreq-fga-unb/2023.2-GummyLog#22]
O ritmo sustentável não determina 40h, e sim, tem 40h como exemplo. 
A ideia aqui, é que a equipe trabalhe de maneira sustentável dentro de suas características, ou seja, 6horas, 8 horas, 10horas, ... e dentro desse parâmetro manter o ritmo. E, não trabalhar 1 hora em uma semana e na outra 20 horas.

![image](https://github.com/mdsreq-fga-unb/2023.2-GummyLog/assets/68402547/0963a981-1170-4059-997f-058a64f4a4f4)

**Comment by Dridr1** [comment]
Alterações solicitadas realizadas na documentação
